[package]
name = "moltenvk_deps"
version = "0.1.0"
authors = ["Tom Gowan <s3549186@student.rmit.edu.au>"]
edition = "2018"

[build-dependencies]
env_perm = { path = "../env_perm" }
dirs = "1.0"
reqwest ="0.9"

[dependencies]

