[package]
name = "moltenvk_deps"
version = "0.1.0"
authors = ["Tom Gowan <tomrgowan@gmail.com>"]
edition = "2018"

[dependencies]
env_perm = { git = "https://github.com/freesig/env_perm.git" }
dirs = "1.0"
curl = "0.4"
tempdir = "0.3"
